project 'LoginApp.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
use_frameworks!

target 'LoginApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.7'
  pod 'Moya', '~> 11.0'
  pod 'SnapKit', '~> 4.0.0'

  # Pods for LoginApp

end
